config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews
  end
end
# Prefix Verb   URI Pattern                            Controller#Action
# restaurants GET    /restaurants(.:format)                 restaurants#index
#             POST   /restaurants(.:format)                 restaurants#create
# new_restaurant GET    /restaurants/new(.:format)             restaurants#new
# edit_restaurant GET    /restaurants/:id/edit(.:format)        restaurants#edit
#  restaurant GET    /restaurants/:id(.:format)             restaurants#show
#             PATCH  /restaurants/:id(.:format)             restaurants#update
#             PUT    /restaurants/:id(.:format)             restaurants#update
#             DELETE /restaurants/:id(.:format)             restaurants#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :phone_number, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: "Restaurant was successfully updated."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category, collection: Restaurant::CATEGORIES %>
<%= f.submit %>


<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
<li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category, collection: Restaurant::CATEGORIES %>
<%= f.submit %>


<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h2>Address</h2>
<p><%= @restaurant.address %></p>

<h2>Phone number : </h2>
<p><%= @restaurant.phone_number %></p>

<h2>Category of the restaurant</h2>
<p><%= @restaurant.category %></p>




 <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>

<div>
<ul>
    <% @restaurant.reviews.each do |review|%>
      <li> <%= review.content %></li>
    <% end %>
  </ul>
</div>

<%= link_to "Return Restaurant List", restaurants_path%>

app/views/reviews/new.html.erb
<h1>#Review</h1>